### PR TITLE
Add {absolutePath} variable to CompactErrorFormatter

### PR DESCRIPTION
**Pull request by enumag**
I need the absolute path to the file in my formatter.

### CODE REVIEW

**Comment by enumag** [comment]
ping @jkuchar 

Maybe the names should be different. Not sure.

**Comment by jkuchar** [comment]
Hi! I’m sorry for late reply. File and path naming is misleading as their meaning is almost the same. What about naming absolute path `absolutePath`?

**Comment by enumag** [comment]
@jkuchar done!

**Comment by jkuchar** [comment]
Thank you 🙂
https://github.com/grifart/phpstan-oneline/releases/tag/v0.2.2

**Pull request merged**
